import { Inter } from 'next/font/google'
import './globals.css'
import LayoutProvider from '@/app/components/LayoutProvider';
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function RootLayout({ children }) {
  const cookieStore = cookies()
  const username = cookieStore.get('username')
  return (
    <html>
      <body className={inter.className}>
        <LayoutProvider username={username}>
          {children}
        </LayoutProvider>
      </body>
    </html>
  );
}

export default RootLayout;